accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignupPageView.as_view(), name="signup"),
    path("<str:username>/", views.user_profile_view, name="user_profile"),
    path(
        "<str:username>/edit_personal/",
        views.user_edit_personal_view,
        name="user_edit_personal",
    ),
    path(
        "<str:username>/edit_address/",
        views.user_edit_address_view,
        name="user_edit_address",
    ),
    path(
        "<str:username>/edit_address/form/<int:address_id>",
        views.user_edit_address_form_view,
        name="user_edit_address_form",
    ),
    path(
        "<str:username>/edit_address/form/add",
        views.user_add_address_form_view,
        name="user_add_address_form",
    ),
    path(
        "<str:username>/edit_address/<int:address_id>/delete/",
        views.user_delete_address_view,
        name="user_delete_address",
    ),
    path(
        "<str:username>/edit_phone/",
        views.user_edit_phone_view,
        name="user_edit_phone",
    ),
    path(
        "<str:username>/edit_phone/form/<int:phone_id>",
        views.user_edit_phone_form_view,
        name="user_edit_phone_form",
    ),
    path(
        "<str:username>/edit_phone/form/add",
        views.user_add_phone_form_view,
        name="user_add_phone_form",
    ),
    path(
        "<str:username>/edit_phone/<int:phone_id>/delete/",
        views.user_delete_phone_view,
        name="user_delete_phone",
    ),
]

core/urls.py
from django.urls import path
from . import views


app_name = "core"
urlpatterns = [
    path("", views.index_page_view, name="index"),
    path("about/", views.about_page_view, name="about"),
    path("contact/", views.contact_page_view, name="contact"),
    path("vendor/", views.vendor_page_view, name="vendor"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("products/", include("products.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/user/edit_address.html
{% extends 'base/base.html' %}

{% block title %}
{{user.username}} | Edit Adress
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Edit Adress form here</h2>
                    <hr>
                    <div class="container d-flex text-center m-2">
                        {% for address in addres_list %}
                        <div class="container">
                            <div>{{address.address_title}}</div>
                            <div>{{address.address_line_1}}</div>
                            <div>{{address.address_line_2}}</div>
                            <div>{{address.city}}</div>
                            <div>{{address.postal_code}}</div>
                            <div>{{address.state}}</div>
                            <div>{{address.country}}</div>
                            <a href="{% url 'accounts:user_edit_address_form' user.username address.id %}"
                                class="btn btn-primary">Edit</a>
                            <a href="{% url 'accounts:user_delete_address' user.username address.id %}"
                                class="btn btn-danger">Delete</a>
                        </div>
                        {% endfor %}
                        <div class="container">
                            <a href="{% url 'accounts:user_add_address_form' user.username %}" class="btn btn-primary">+
                                Add new</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/edit_address_form.html
{% extends 'base/base.html' %}

{% block title %}
{{user.username}} | Edit Address
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Edit Address</h2>
                    <hr>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/edit_personal.html
{% extends 'base/base.html' %}

{% block title %}
{{user.username}} | Edit Personal
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Edit personal information</h2>
                    <hr>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/edit_phone.html
{% extends 'base/base.html' %}

{% block title %}
{{user.username}} | Edit Phone
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Edit Phone Numbers</h2>
                    <hr>
                    <div class="container d-flex text-center m-2">
                        {% for phone in phone_list %}
                        <div class="container">
                            <div>{{phone.phone_title}}</div>
                            <div>{{phone.number}}</div>
                            <a href="{% url 'accounts:user_edit_phone_form' user.username phone.id %}"
                                class="btn btn-primary">Edit</a>
                            <a href="{% url 'accounts:user_delete_phone' user.username phone.id %}"
                                class="btn btn-danger">Delete</a>
                        </div>
                        {% endfor %}
                        <div class="container">
                            <a href="{% url 'accounts:user_add_phone_form' user.username %}" class="btn btn-primary">
                                + Add new
                            </a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/edit_phone_form.html
{% extends 'base/base.html' %}

{% block title %}
{{user.username}} | Edit Phone
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Edit Phone</h2>
                    <hr>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/profile.html
{% extends 'base/base.html' %}

{% block title %}
Green Market | {{user.username}}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row flex-nowrap">
        {% include 'user/sidebar.html' %}
        <div class=" col py-3">
            <div class="vh-100 m-auto mt-4 justify-content-center">
                <div>
                    <h2 class="text-center">Personal information</h2>
                    <div>username: {{user.username}}</div>
                    <div>first name: {{user.first_name}}</div>
                    <div>last name: {{user.last_name}}</div>
                    <br>
                    <br>
                </div>
                <div class="mt-3">
                    <h2 class="text-center">Addres</h2>
                    <hr>
                    <div class="container d-flex text-center m-2">
                        {% for address in addres_list %}
                        <div class="container">
                            <div>{{address.address_title}}</div>
                            <div>{{address.address_line_1}}</div>
                            <div>{{address.address_line_2}}</div>
                            <div>{{address.city}}</div>
                            <div>{{address.postal_code}}</div>
                            <div>{{address.state}}</div>
                            <div>{{address.country}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="mt-3">
                    <h2 class="text-center">Phone number</h2>
                    <hr>
                    <div class="container d-flex text-center m-2">
                        {% for number in phone_list %}
                        <div class="container">
                            <div>{{number.phone_title}}</div>
                            <div>{{number.number}}</div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'base/footer.html' %}
{% endblock %}

templates/user/sidebar.html
<div class="col-auto px-sm-2 px-0 h-500px bg-primary">
    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2">
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
                <a href="{% url 'accounts:user_profile' user.username %}"
                    class="nav-link align-middle px-0 text-white">{{user.username}} profile</a>
            </li>
            <li>
                <hr>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:user_edit_personal' user.username %}"
                    class="nav-link align-middle px-0 text-white">Edit personal info</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:user_edit_address' user.username %}"
                    class="nav-link align-middle px-0 text-white">Edit adresses</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'accounts:user_edit_phone' user.username %}"
                    class="nav-link align-middle px-0 text-white">Edit phone numbers</a>
            </li>
            <li>
                <hr>
            </li>
            <li class="nav-item">
                <a href="{% url 'password_change' %}" class="nav-link align-middle px-0 text-white">Change
                    password</a>
            </li>
        </ul>
    </div>
</div>